a <- c(14,7,6,5)
name <- c("zhangsan","lisi","lijin","liupin")
d <- c(7,120,28,3)
lang <- c("PHP","go","PHP","R")
y <- data.frame(a,name,d,lang)
print(y)
print(y$a)

table(y$name,y$lang)
summary(y$name)
# plot(y$name,y$lang)
plot(y$d,type="o",col = "red",xlab="x",ylab="y",main="")
lines(y$a, type = "o", col = "blue")
dev.off()
